name: happyhour_app
description: Find happy hour deals in Reykjavik
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0-276.0.dev

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_cache_manager: ^3.4.1
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.1.0
  geolocator: ^14.0.0
  go_router: ^15.1.0
  google_fonts: ^6.3.3
  http: ^1.3.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  latlong2: ^0.9.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  custom_lint: ^0.8.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0
  lint: ^2.3.0
  mocktail: ^1.0.4

flutter:
  generate: true
  uses-material-design: true
